/*
* Note: this file originally auto-generated by mib2c using
*       version : 1.0.0 $ of : mib2c.snmp_subagent.conf $ zhongjh@huahuan.com
*/
#if 0
#ifndef _SNMP_SUBAGENT_H_
#define _SNMP_SUBAGENT_H_

void snmp_subagent_init(void);

int snmp_subagent_tick(int block);

void snmp_subagent_shutdown(void);


#endif
#endif
