#ifndef _GPN_SOCK_COMM_ROLE_MAN_H_
#define _GPN_SOCK_COMM_ROLE_MAN_H_

#ifdef    __cplusplus
extern "C"
{
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <sys/un.h>
//#include <arpa/inet.h>
#include <netinet/in.h>

#include "lib/gpnSocket/socketComm/gpnSockCommUnifyPath.h"

#include "lib/gpnSocket/socketComm/gpnSockTypeDef.h"
#include "lib/gpnSocket/socketComm/gpnSelectOpt.h"
#include "lib/gpnSocket/socketComm/gpnSockCommModuDef.h"

#include "lib/gpnDevInfo/devCoreInfo/gpnDevCoreInfo.h"


#define GPN_SOCK_ROLE_MAN_OK                    GPN_SOCK_SYS_OK
#define GPN_SOCK_ROLE_MAN_ERR                   GPN_SOCK_SYS_ERR

#define GPN_SOCK_ROLE_MAN_YES                   GPN_SOCK_SYS_OK
#define GPN_SOCK_ROLE_MAN_NO                    GPN_SOCK_SYS_ERR

#define GPN_SOCK_ROLE_MAN_ENABLE                GPN_SOCK_SYS_ENABLE
#define GPN_SOCK_ROLE_MAN_DISABLE               GPN_SOCK_SYS_DISABLE

#define GPN_ENABLE                              (GPN_SOCK_ROLE_MAN_ENABLE)
#define GPN_DISABLE                             (GPN_SOCK_ROLE_MAN_DISABLE)
#define GPN_SERVER                              (GPN_ENABLE + GPN_DISABLE)


#define GPN_SOCK_ROLE_PRINT(level, info...)     GEN_SOCK_SYS_PRINT((level), info)
#define GPN_SOCK_ROLE_AGP                       GEN_SOCK_SYS_AGP
#define GPN_SOCK_ROLE_SVP                       GEN_SOCK_SYS_SVP
#define GPN_SOCK_ROLE_CMP                       GEN_SOCK_SYS_CMP
#define GPN_SOCK_ROLE_CUP                       GEN_SOCK_SYS_CUP

/*gpn_socket UNIX fd name MAX lenth*/
#define GPN_SOCK_UNIX_PATH_MAX                  108

#define GPN_UINX_SOCK_FD_NAME_LEN               GPN_SOCK_UNIX_PATH_MAX/*GPN_SOCK_ADDR_UN_LEN ???*/

/*gpn_socket comm role define*/
#define GPN_SOCK_FD_ROLE_NULL                   0
#define GPN_SOCK_FD_ROLE_ASYN_SEV               1
#define GPN_SOCK_FD_ROLE_SYN_SEV                2
#define GPN_SOCK_FD_ROLE_CLI                    3

/******************************************************************************************************/
/*                                                                    GPN_SOCKET Role Format                                                                          */
/******************************************************************************************************/
/*bit |31|30|29|28|27|26|25|24|23|22|21|20|19|18|17|16|15|14|13|12|11|10|09|08|07|06|05|04|03|02|21|00| */
/*                     gpn_socket's run place filed                               |                          gpn_socket's module role filed                  */
/******************************************************************************************************/

/*gpn_socket comm run place define*/
/******************************************************************************************************/
#define GPN_SOCK_RUN_PLACE_NULL                 0
#define GPN_SOCK_RUN_PLACE_IND                  1
#define GPN_SOCK_RUN_PLACE_SUB                  2
#define GPN_SOCK_RUN_PLACE_NMA                  3
#define GPN_SOCK_RUN_PLACE_NMB                  4
#define GPN_SOCK_RUN_PLACE_SWA                  5
#define GPN_SOCK_RUN_PLACE_SWB                  6
#define GPN_SOCK_RUN_PLACE_ALL                  7

#define GPN_COMM_ROLE_RUN_MASK                  0x0000FFFF
#define GPN_COMM_ROLE_RUN_SHIFT                 16
/*=============================================================================================================*/
/*=============================================================================================================*/
#define GPN_COMM_ROLE_RUN_FILED_IND             ((GPN_SOCK_RUN_PLACE_IND & GPN_COMM_ROLE_RUN_MASK) << GPN_COMM_ROLE_RUN_SHIFT)
/*instance module runing in independence device*/
#define GPN_COMM_ROLE_RUN_FILED_SUB             ((GPN_SOCK_RUN_PLACE_SUB & GPN_COMM_ROLE_RUN_MASK) << GPN_COMM_ROLE_RUN_SHIFT)
/*instance module runing in NMa*/
#define GPN_COMM_ROLE_RUN_FILED_NMA             ((GPN_SOCK_RUN_PLACE_NMA & GPN_COMM_ROLE_RUN_MASK) << GPN_COMM_ROLE_RUN_SHIFT)
/*instance module runing in NMb*/
#define GPN_COMM_ROLE_RUN_FILED_NMB             ((GPN_SOCK_RUN_PLACE_NMB & GPN_COMM_ROLE_RUN_MASK) << GPN_COMM_ROLE_RUN_SHIFT)
/*instance module runing in SWIa (SP SUB)*/
#define GPN_COMM_ROLE_RUN_FILED_SWA             ((GPN_SOCK_RUN_PLACE_SWA & GPN_COMM_ROLE_RUN_MASK) << GPN_COMM_ROLE_RUN_SHIFT)
/*instance module runing in SWIb (SP SUB)*/
#define GPN_COMM_ROLE_RUN_FILED_SWB             ((GPN_SOCK_RUN_PLACE_SWB & GPN_COMM_ROLE_RUN_MASK) << GPN_COMM_ROLE_RUN_SHIFT)
/*=============================================================================================================*/

/*gpn_socket comm module role define*/
/******************************************************************************************************/
#define GPN_SOCK_ROLE_TRANS                     (GPN_COMMM_TRANSFER)
#define GPN_SOCK_ROLE_NM_SYN                    (GPN_COMMM_NM_SYN)
#define GPN_SOCK_ROLE_SHELL                     (GPN_COMMM_TERM_SHELL)
#define GPN_SOCK_ROLE_ALM                       (GPN_COMMM_ALM)
#define GPN_SOCK_ROLE_IFM                       (GPN_COMMM_IFM)
#define GPN_SOCK_ROLE_SDM                       (GPN_COMMM_SDM)
#define GPN_SOCK_ROLE_NSM                       (GPN_COMMM_NSM)
#define GPN_SOCK_ROLE_ONMD                      (GPN_COMMM_ONMD)
#define GPN_SOCK_ROLE_LAG                       (GPN_COMMM_LAG)
#define GPN_SOCK_ROLE_PWE                       (GPN_COMMM_PWE)
#define GPN_SOCK_ROLE_INIT                      (GPN_COMMM_INIT)
#define GPN_SOCK_ROLE_STAT                      (GPN_COMMM_STAT)
#define GPN_SOCK_ROLE_CFGMGT                    (GPN_COMMM_CFGMGT)
#define GPN_SOCK_ROLE_SYSMGT                    (GPN_COMMM_SYSMGT)
#define GPN_SOCK_ROLE_FT                        (GPN_COMMM_FT)
#define GPN_SOCK_ROLE_OAMD                      (GPN_COMMM_OAMD)
#define GPN_SOCK_ROLE_SYNCED                    (GPN_COMMM_SYNCED)
#define GPN_SOCK_ROLE_COPROC                    (GPN_COMMM_COPROC)
#define GPN_SOCK_ROLE_XLOAD                     (GPN_COMMM_XLOAD)
#define GPN_SOCK_ROLE_IMI                       (GPN_COMMM_IMI)

/***************** lipf add for ipran ******************************/
#define GPN_SOCK_ROLE_MPLS                      (GPN_COMMM_MPLS)
#define GPN_SOCK_ROLE_CLOCK                     (GPN_COMMM_CLOCK)
#define GPN_SOCK_ROLE_SYSTEM                    (GPN_COMMM_SYSTEM)
#define GPN_SOCK_ROLE_DEVM                      (GPN_COMMM_DEVM)
#define GPN_SOCK_ROLE_HAL                       (GPN_COMMM_HAL)
#define GPN_SOCK_ROLE_L2                        (GPN_COMMM_L2)
#define GPN_SOCK_ROLE_CES                       (GPN_COMMM_CES)
#define GPN_SOCK_ROLE_VTYSH                     (GPN_COMMM_VTYSH)
#define GPN_SOCK_ROLE_FTM                       (GPN_COMMM_FTM)
/********************** end ***************************************/


/*above is valid instance role */
#define GPN_SOCK_VALID_INS_ROLE_ID_MAX          (GPN_VALID_INS_COMM_ROLE_ID_MAX)

#if 0
#define GPN_SOCK_ROLE_RESERVED04                (GPN_COMMM_RESERVED04)/*reserved link modu, do not use now*/
#define GPN_SOCK_ROLE_RESERVED05                (GPN_COMMM_RESERVED05)
#define GPN_SOCK_ROLE_RESERVED06                (GPN_COMMM_RESERVED06)
#define GPN_SOCK_ROLE_RESERVED07                (GPN_COMMM_RESERVED07)
#define GPN_SOCK_ROLE_RESERVED08                (GPN_COMMM_RESERVED08)
#define GPN_SOCK_ROLE_RESERVED09                (GPN_COMMM_RESERVED09)
#define GPN_SOCK_ROLE_RESERVED10                (GPN_COMMM_RESERVED10)
#define GPN_SOCK_ROLE_RESERVED11                (GPN_COMMM_RESERVED11)
#define GPN_SOCK_ROLE_RESERVED12                (GPN_COMMM_RESERVED12)
#endif
#define GPN_SOCK_ROLE_RESERVED13                (GPN_COMMM_RESERVED13)
#define GPN_SOCK_ROLE_RESERVED14                (GPN_COMMM_RESERVED14)
#define GPN_SOCK_ROLE_RESERVED15                (GPN_COMMM_RESERVED15)
#define GPN_SOCK_ROLE_RESERVED16                (GPN_COMMM_RESERVED16)
#define GPN_SOCK_ROLE_RESERVED17                (GPN_COMMM_RESERVED17)
#define GPN_SOCK_ROLE_RESERVED18                (GPN_COMMM_RESERVED18)
#define GPN_SOCK_ROLE_RESERVED19                (GPN_COMMM_RESERVED19)
#define GPN_SOCK_ROLE_RESERVED20                (GPN_COMMM_RESERVED20)
#define GPN_SOCK_ROLE_RESERVED21                (GPN_COMMM_RESERVED21)
#define GPN_SOCK_ROLE_RESERVED22                (GPN_COMMM_RESERVED22)
#define GPN_SOCK_ROLE_RESERVED23                (GPN_COMMM_RESERVED23)
#define GPN_SOCK_ROLE_RESERVED24                (GPN_COMMM_RESERVED24)
#define GPN_SOCK_ROLE_RESERVED25                (GPN_COMMM_RESERVED25)
#define GPN_SOCK_ROLE_RESERVED26                (GPN_COMMM_RESERVED26)
#define GPN_SOCK_ROLE_RESERVED27                (GPN_COMMM_RESERVED27)
#define GPN_SOCK_ROLE_RESERVED28                (GPN_COMMM_RESERVED28)
#define GPN_SOCK_ROLE_RESERVED29                (GPN_COMMM_RESERVED29)
#define GPN_SOCK_ROLE_RESERVED30                (GPN_COMMM_RESERVED30)
#define GPN_SOCK_ROLE_RESERVED31                (GPN_COMMM_RESERVED31)
#define GPN_SOCK_ROLE_RESERVED32                (GPN_COMMM_RESERVED32)
#define GPN_SOCK_ROLE_RESERVED33                (GPN_COMMM_RESERVED33)
#define GPN_SOCK_ROLE_RESERVED34                (GPN_COMMM_RESERVED34)
#define GPN_SOCK_ROLE_RESERVED35                (GPN_COMMM_RESERVED35)
#define GPN_SOCK_ROLE_RESERVED36                (GPN_COMMM_RESERVED36)
#define GPN_SOCK_ROLE_RESERVED37                (GPN_COMMM_RESERVED37)
#define GPN_SOCK_ROLE_RESERVED38                (GPN_COMMM_RESERVED38)
#define GPN_SOCK_ROLE_RESERVED39                (GPN_COMMM_RESERVED39)
#define GPN_SOCK_ROLE_RESERVED40                (GPN_COMMM_RESERVED40)
#define GPN_SOCK_ROLE_RESERVED41                (GPN_COMMM_RESERVED41)
#define GPN_SOCK_ROLE_RESERVED42                (GPN_COMMM_RESERVED42)
#define GPN_SOCK_ROLE_RESERVED43                (GPN_COMMM_RESERVED43)
#define GPN_SOCK_ROLE_RESERVED44                (GPN_COMMM_RESERVED44)
#define GPN_SOCK_ROLE_RESERVED45                (GPN_COMMM_RESERVED45)
#define GPN_SOCK_ROLE_RESERVED46                (GPN_COMMM_RESERVED46)
#define GPN_SOCK_ROLE_RESERVED47                (GPN_COMMM_RESERVED47)

/*above is instance role */
#define GPN_SOCK_INS_ROLE_ID_MAX                (GPN_INS_COMM_ROLE_ID_MAX)

#define GPN_SOCK_ROLE_TIMER_SEV                 (GPN_COMMM_TIMER_SEV)/*default link modu, do not use creat communication role*/

/*above is real role */
#define GPN_SOCK_REA_ROLE_ID_MAX                (GPN_REA_COMM_ROLE_ID_MAX)

#define GPN_SOCK_ROLE_NM_TO_SUB1T               (GPN_COMMM_NM_TO_SUB1T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB2T               (GPN_COMMM_NM_TO_SUB2T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB3T               (GPN_COMMM_NM_TO_SUB3T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB4T               (GPN_COMMM_NM_TO_SUB4T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB5T               (GPN_COMMM_NM_TO_SUB5T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB6T               (GPN_COMMM_NM_TO_SUB6T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB7T               (GPN_COMMM_NM_TO_SUB7T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB8T               (GPN_COMMM_NM_TO_SUB8T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB9T               (GPN_COMMM_NM_TO_SUB9T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB10T              (GPN_COMMM_NM_TO_SUB10T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB11T              (GPN_COMMM_NM_TO_SUB11T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB12T              (GPN_COMMM_NM_TO_SUB12T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB13T              (GPN_COMMM_NM_TO_SUB13T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB14T              (GPN_COMMM_NM_TO_SUB14T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB15T              (GPN_COMMM_NM_TO_SUB15T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB16T              (GPN_COMMM_NM_TO_SUB16T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB17T              (GPN_COMMM_NM_TO_SUB17T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB18T              (GPN_COMMM_NM_TO_SUB18T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB19T              (GPN_COMMM_NM_TO_SUB19T)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB20T              (GPN_COMMM_NM_TO_SUB20T)/*do not use as process role*/

/*above is Slot-Bettewen-Transfer role */
#define GPN_SOCK_TRS_ROLE_ID_MAX                (GPN_TRS_COMM_ROLE_ID_MAX)

#define GPN_SOCK_ROLE_NM_TO_SUB1F               (GPN_COMMM_NM_TO_SUB1F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB2F               (GPN_COMMM_NM_TO_SUB2F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB3F               (GPN_COMMM_NM_TO_SUB3F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB4F               (GPN_COMMM_NM_TO_SUB4F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB5F               (GPN_COMMM_NM_TO_SUB5F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB6F               (GPN_COMMM_NM_TO_SUB6F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB7F               (GPN_COMMM_NM_TO_SUB7F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB8F               (GPN_COMMM_NM_TO_SUB8F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB9F               (GPN_COMMM_NM_TO_SUB9F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB10F              (GPN_COMMM_NM_TO_SUB10F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB11F              (GPN_COMMM_NM_TO_SUB11F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB12F              (GPN_COMMM_NM_TO_SUB12F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB13F              (GPN_COMMM_NM_TO_SUB13F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB14F              (GPN_COMMM_NM_TO_SUB14F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB15F              (GPN_COMMM_NM_TO_SUB15F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB16F              (GPN_COMMM_NM_TO_SUB16F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB17F              (GPN_COMMM_NM_TO_SUB17F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB18F              (GPN_COMMM_NM_TO_SUB18F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB19F              (GPN_COMMM_NM_TO_SUB19F)/*do not use as process role*/
#define GPN_SOCK_ROLE_NM_TO_SUB20F              (GPN_COMMM_NM_TO_SUB20F)/*do not use as process role*/

/*above is slot-bettewen-file-transfer role */
#define GPN_SOCK_FT_ROLE_ID_MAX                 (GPN_FT_COMM_ROLE_ID_MAX)

#define GPN_SOCK_ROLE_SYN_TO_NMA                (GPN_COMMM_SYN_TO_NMA)/*do not use as process role*/
#define GPN_SOCK_ROLE_SYN_TO_NMB                (GPN_COMMM_SYN_TO_NMB)/*do not use as process role*/

/*above is syn-bettewen-nm role */
#define GPN_SOCK_SYN_ROLE_ID_MAX                (GPN_SYN_COMM_ROLE_ID_MAX)


/*above is all role */
#define GPN_SOCK_ALL_ROLE_ID_MAX                (GPN_COMM_ROLE_ID_MAX)



#define GPN_COMM_ROLE_MODU_MASK					0x0000FFFF
#define GPN_COMM_ROLE_MODU_SHIFT				0
/*=============================================================================================================*/
/*=============================================================================================================*/
#define GPN_COMM_ROLE_FILED_TRANS               ((GPN_SOCK_ROLE_TRANS & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_NM_SYN              ((GPN_SOCK_ROLE_NM_SYN & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_SHELL               ((GPN_SOCK_ROLE_SHELL & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_ALM                 ((GPN_SOCK_ROLE_ALM & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_IFM                 ((GPN_SOCK_ROLE_IFM & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_SDM                 ((GPN_SOCK_ROLE_SDM & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_NSM                 ((GPN_SOCK_ROLE_NSM & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_ONMD                ((GPN_SOCK_ROLE_ONMD & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_LAG                 ((GPN_SOCK_ROLE_LAG & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_PWE                 ((GPN_SOCK_ROLE_PWE & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_INIT                ((GPN_SOCK_ROLE_INIT & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_STAT                ((GPN_SOCK_ROLE_STAT & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_CFGMGT              ((GPN_SOCK_ROLE_CFGMGT & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_SYSMGT              ((GPN_SOCK_ROLE_SYSMGT & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_FT                  ((GPN_SOCK_ROLE_FT & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_OAMD                ((GPN_SOCK_ROLE_OAMD & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_SYNCED              ((GPN_SOCK_ROLE_SYNCED & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_COPROC              ((GPN_SOCK_ROLE_COPROC & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_XLOAD               ((GPN_SOCK_ROLE_XLOAD & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_IMI                 ((GPN_SOCK_ROLE_IMI & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)

/***************** lipf add for ipran ******************************/
#define GPN_COMM_ROLE_FILED_MPLS                ((GPN_SOCK_ROLE_MPLS & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_CLOCK               ((GPN_SOCK_ROLE_CLOCK & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_SYSTEM              ((GPN_SOCK_ROLE_SYSTEM & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_DEVM                ((GPN_SOCK_ROLE_DEVM & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_HAL                 ((GPN_SOCK_ROLE_HAL & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_L2                  ((GPN_SOCK_ROLE_L2 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_CES                 ((GPN_SOCK_ROLE_CES & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_VTYSH               ((GPN_SOCK_ROLE_VTYSH & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_FTM                 ((GPN_SOCK_ROLE_FTM & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)

/************************ end **************************************/

#if 0
#define GPN_COMM_ROLE_FILED_RESERVED04          ((GPN_SOCK_ROLE_RESERVED04 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED05          ((GPN_SOCK_ROLE_RESERVED05 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED06          ((GPN_SOCK_ROLE_RESERVED06 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED07          ((GPN_SOCK_ROLE_RESERVED07 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED08          ((GPN_SOCK_ROLE_RESERVED08 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED09          ((GPN_SOCK_ROLE_RESERVED09 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED10          ((GPN_SOCK_ROLE_RESERVED10 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED11          ((GPN_SOCK_ROLE_RESERVED11 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED12          ((GPN_SOCK_ROLE_RESERVED12 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#endif
#define GPN_COMM_ROLE_FILED_RESERVED13          ((GPN_SOCK_ROLE_RESERVED13 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED14          ((GPN_SOCK_ROLE_RESERVED14 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED15          ((GPN_SOCK_ROLE_RESERVED15 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED16          ((GPN_SOCK_ROLE_RESERVED16 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED17          ((GPN_SOCK_ROLE_RESERVED17 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED18          ((GPN_SOCK_ROLE_RESERVED18 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED19          ((GPN_SOCK_ROLE_RESERVED19 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED20          ((GPN_SOCK_ROLE_RESERVED20 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED21          ((GPN_SOCK_ROLE_RESERVED21 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED22          ((GPN_SOCK_ROLE_RESERVED22 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED23          ((GPN_SOCK_ROLE_RESERVED23 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED24          ((GPN_SOCK_ROLE_RESERVED24 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED25          ((GPN_SOCK_ROLE_RESERVED25 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED26          ((GPN_SOCK_ROLE_RESERVED26 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED27          ((GPN_SOCK_ROLE_RESERVED27 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED28          ((GPN_SOCK_ROLE_RESERVED28 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED29          ((GPN_SOCK_ROLE_RESERVED29 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED30          ((GPN_SOCK_ROLE_RESERVED30 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED31          ((GPN_SOCK_ROLE_RESERVED31 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED32          ((GPN_SOCK_ROLE_RESERVED32 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED33          ((GPN_SOCK_ROLE_RESERVED33 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED34          ((GPN_SOCK_ROLE_RESERVED34 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED35          ((GPN_SOCK_ROLE_RESERVED35 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED36          ((GPN_SOCK_ROLE_RESERVED36 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED37          ((GPN_SOCK_ROLE_RESERVED37 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED38          ((GPN_SOCK_ROLE_RESERVED38 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED39          ((GPN_SOCK_ROLE_RESERVED39 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED40          ((GPN_SOCK_ROLE_RESERVED40 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED41          ((GPN_SOCK_ROLE_RESERVED41 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED42          ((GPN_SOCK_ROLE_RESERVED42 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED43          ((GPN_SOCK_ROLE_RESERVED43 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED44          ((GPN_SOCK_ROLE_RESERVED44 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED45          ((GPN_SOCK_ROLE_RESERVED45 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED46          ((GPN_SOCK_ROLE_RESERVED46 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)
#define GPN_COMM_ROLE_FILED_RESERVED47          ((GPN_SOCK_ROLE_RESERVED47 & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)

#define GPN_COMM_ROLE_FILED_TIMER_SEV           ((GPN_SOCK_ROLE_TIMER_SEV & GPN_COMM_ROLE_MODU_MASK) << GPN_COMM_ROLE_MODU_SHIFT)

/*=============================================================================================================*/


/*define witch comm module run in withc run place, so that is COMM_ROLE*/
/*=============================================================================================================*/
/*=============================================================================================================*/
#define GPN_COMM_ROLE_TRANS_ON_SUB 				(GPN_COMM_ROLE_FILED_TRANS|GPN_COMM_ROLE_RUN_FILED_SUB)
#define GPN_COMM_ROLE_TRANS_ON_IND 				(GPN_COMM_ROLE_FILED_TRANS|GPN_COMM_ROLE_RUN_FILED_IND)
#define GPN_COMM_ROLE_TRANS_ON_NMA 				(GPN_COMM_ROLE_FILED_TRANS|GPN_COMM_ROLE_RUN_FILED_NMA)
#define GPN_COMM_ROLE_TRANS_ON_NMB 				(GPN_COMM_ROLE_FILED_TRANS|GPN_COMM_ROLE_RUN_FILED_NMB)
#define GPN_COMM_ROLE_TRANS_ON_SWA 				(GPN_COMM_ROLE_FILED_TRANS|GPN_COMM_ROLE_RUN_FILED_SWA)
#define GPN_COMM_ROLE_TRANS_ON_SWB 				(GPN_COMM_ROLE_FILED_TRANS|GPN_COMM_ROLE_RUN_FILED_SWB)

#define GPN_COMM_ROLE_NM_SYN_ON_SUB 			(GPN_COMM_ROLE_FILED_NM_SYN|GPN_COMM_ROLE_RUN_FILED_SUB)
#define GPN_COMM_ROLE_NM_SYN_ON_IND 			(GPN_COMM_ROLE_FILED_NM_SYN|GPN_COMM_ROLE_RUN_FILED_IND)
#define GPN_COMM_ROLE_NM_SYN_ON_NMA 			(GPN_COMM_ROLE_FILED_NM_SYN|GPN_COMM_ROLE_RUN_FILED_NMA)
#define GPN_COMM_ROLE_NM_SYN_ON_NMB 			(GPN_COMM_ROLE_FILED_NM_SYN|GPN_COMM_ROLE_RUN_FILED_NMB)
#define GPN_COMM_ROLE_NM_SYN_ON_SWA 			(GPN_COMM_ROLE_FILED_NM_SYN|GPN_COMM_ROLE_RUN_FILED_SWA)
#define GPN_COMM_ROLE_NM_SYN_ON_SWB 			(GPN_COMM_ROLE_FILED_NM_SYN|GPN_COMM_ROLE_RUN_FILED_SWB)

#define GPN_COMM_ROLE_SHELL_ON_SUB 				(GPN_COMM_ROLE_FILED_SHELL|GPN_COMM_ROLE_RUN_FILED_SUB)
#define GPN_COMM_ROLE_SHELL_ON_IND 				(GPN_COMM_ROLE_FILED_SHELL|GPN_COMM_ROLE_RUN_FILED_IND)
#define GPN_COMM_ROLE_SHELL_ON_NMA 				(GPN_COMM_ROLE_FILED_SHELL|GPN_COMM_ROLE_RUN_FILED_NMA)
#define GPN_COMM_ROLE_SHELL_ON_NMB 				(GPN_COMM_ROLE_FILED_SHELL|GPN_COMM_ROLE_RUN_FILED_NMB)
#define GPN_COMM_ROLE_SHELL_ON_SWA 				(GPN_COMM_ROLE_FILED_SHELL|GPN_COMM_ROLE_RUN_FILED_SWA)
#define GPN_COMM_ROLE_SHELL_ON_SWB 				(GPN_COMM_ROLE_FILED_SHELL|GPN_COMM_ROLE_RUN_FILED_SWB)

#define GPN_COMM_ROLE_ALM_ON_SUB 				(GPN_COMM_ROLE_FILED_ALM|GPN_COMM_ROLE_RUN_FILED_SUB)
#define GPN_COMM_ROLE_ALM_ON_IND 				(GPN_COMM_ROLE_FILED_ALM|GPN_COMM_ROLE_RUN_FILED_IND)
#define GPN_COMM_ROLE_ALM_ON_NMA 				(GPN_COMM_ROLE_FILED_ALM|GPN_COMM_ROLE_RUN_FILED_NMA)
#define GPN_COMM_ROLE_ALM_ON_NMB 				(GPN_COMM_ROLE_FILED_ALM|GPN_COMM_ROLE_RUN_FILED_NMB)
#define GPN_COMM_ROLE_ALM_ON_SWA 				(GPN_COMM_ROLE_FILED_ALM|GPN_COMM_ROLE_RUN_FILED_SWA)
#define GPN_COMM_ROLE_ALM_ON_SWB 				(GPN_COMM_ROLE_FILED_ALM|GPN_COMM_ROLE_RUN_FILED_SWB)

#define GPN_COMM_ROLE_IFM_ON_SUB 				(GPN_COMM_ROLE_FILED_IFM|GPN_COMM_ROLE_RUN_FILED_SUB)
#define GPN_COMM_ROLE_IFM_ON_IND 				(GPN_COMM_ROLE_FILED_IFM|GPN_COMM_ROLE_RUN_FILED_IND)
#define GPN_COMM_ROLE_IFM_ON_NMA 				(GPN_COMM_ROLE_FILED_IFM|GPN_COMM_ROLE_RUN_FILED_NMA)
#define GPN_COMM_ROLE_IFM_ON_NMB 				(GPN_COMM_ROLE_FILED_IFM|GPN_COMM_ROLE_RUN_FILED_NMB)
#define GPN_COMM_ROLE_IFM_ON_SWA 				(GPN_COMM_ROLE_FILED_IFM|GPN_COMM_ROLE_RUN_FILED_SWA)
#define GPN_COMM_ROLE_IFM_ON_SWB 				(GPN_COMM_ROLE_FILED_IFM|GPN_COMM_ROLE_RUN_FILED_SWB)

#define GPN_COMM_ROLE_SDM_ON_SUB 				(GPN_COMM_ROLE_FILED_SDM|GPN_COMM_ROLE_RUN_FILED_SUB)
#define GPN_COMM_ROLE_SDM_ON_IND 				(GPN_COMM_ROLE_FILED_SDM|GPN_COMM_ROLE_RUN_FILED_IND)
#define GPN_COMM_ROLE_SDM_ON_NMA 				(GPN_COMM_ROLE_FILED_SDM|GPN_COMM_ROLE_RUN_FILED_NMA)
#define GPN_COMM_ROLE_SDM_ON_NMB 				(GPN_COMM_ROLE_FILED_SDM|GPN_COMM_ROLE_RUN_FILED_NMB)
#define GPN_COMM_ROLE_SDM_ON_SWA 				(GPN_COMM_ROLE_FILED_SDM|GPN_COMM_ROLE_RUN_FILED_SWA)
#define GPN_COMM_ROLE_SDM_ON_SWB 				(GPN_COMM_ROLE_FILED_SDM|GPN_COMM_ROLE_RUN_FILED_SWB)

#define GPN_COMM_ROLE_NSM_ON_SUB 				(GPN_COMM_ROLE_FILED_NSM|GPN_COMM_ROLE_RUN_FILED_SUB)
#define GPN_COMM_ROLE_NSM_ON_IND 				(GPN_COMM_ROLE_FILED_NSM|GPN_COMM_ROLE_RUN_FILED_IND)
#define GPN_COMM_ROLE_NSM_ON_NMA 				(GPN_COMM_ROLE_FILED_NSM|GPN_COMM_ROLE_RUN_FILED_NMA)
#define GPN_COMM_ROLE_NSM_ON_NMB 				(GPN_COMM_ROLE_FILED_NSM|GPN_COMM_ROLE_RUN_FILED_NMB)
#define GPN_COMM_ROLE_NSM_ON_SWA 				(GPN_COMM_ROLE_FILED_NSM|GPN_COMM_ROLE_RUN_FILED_SWA)
#define GPN_COMM_ROLE_NSM_ON_SWB 				(GPN_COMM_ROLE_FILED_NSM|GPN_COMM_ROLE_RUN_FILED_SWB)

#define GPN_COMM_ROLE_ONMD_ON_SUB 				(GPN_COMM_ROLE_FILED_ONMD|GPN_COMM_ROLE_RUN_FILED_SUB)
#define GPN_COMM_ROLE_ONMD_ON_IND 				(GPN_COMM_ROLE_FILED_ONMD|GPN_COMM_ROLE_RUN_FILED_IND)
#define GPN_COMM_ROLE_ONMD_ON_NMA 				(GPN_COMM_ROLE_FILED_ONMD|GPN_COMM_ROLE_RUN_FILED_NMA)
#define GPN_COMM_ROLE_ONMD_ON_NMB 				(GPN_COMM_ROLE_FILED_ONMD|GPN_COMM_ROLE_RUN_FILED_NMB)
#define GPN_COMM_ROLE_ONMD_ON_SWA 				(GPN_COMM_ROLE_FILED_ONMD|GPN_COMM_ROLE_RUN_FILED_SWA)
#define GPN_COMM_ROLE_ONMD_ON_SWB 				(GPN_COMM_ROLE_FILED_ONMD|GPN_COMM_ROLE_RUN_FILED_SWB)

#define GPN_COMM_ROLE_LAG_ON_SUB 				(GPN_COMM_ROLE_FILED_LAG|GPN_COMM_ROLE_RUN_FILED_SUB)
#define GPN_COMM_ROLE_LAG_ON_IND 				(GPN_COMM_ROLE_FILED_LAG|GPN_COMM_ROLE_RUN_FILED_IND)
#define GPN_COMM_ROLE_LAG_ON_NMA 				(GPN_COMM_ROLE_FILED_LAG|GPN_COMM_ROLE_RUN_FILED_NMA)
#define GPN_COMM_ROLE_LAG_ON_NMB 				(GPN_COMM_ROLE_FILED_LAG|GPN_COMM_ROLE_RUN_FILED_NMB)
#define GPN_COMM_ROLE_LAG_ON_SWA 				(GPN_COMM_ROLE_FILED_LAG|GPN_COMM_ROLE_RUN_FILED_SWA)
#define GPN_COMM_ROLE_LAG_ON_SWB 				(GPN_COMM_ROLE_FILED_LAG|GPN_COMM_ROLE_RUN_FILED_SWB)

#define GPN_COMM_ROLE_PWE_ON_SUB 				(GPN_COMM_ROLE_FILED_PWE|GPN_COMM_ROLE_RUN_FILED_SUB)
#define GPN_COMM_ROLE_PWE_ON_IND 				(GPN_COMM_ROLE_FILED_PWE|GPN_COMM_ROLE_RUN_FILED_IND)
#define GPN_COMM_ROLE_PWE_ON_NMA 				(GPN_COMM_ROLE_FILED_PWE|GPN_COMM_ROLE_RUN_FILED_NMA)
#define GPN_COMM_ROLE_PWE_ON_NMB 				(GPN_COMM_ROLE_FILED_PWE|GPN_COMM_ROLE_RUN_FILED_NMB)
#define GPN_COMM_ROLE_PWE_ON_SWA 				(GPN_COMM_ROLE_FILED_PWE|GPN_COMM_ROLE_RUN_FILED_SWA)
#define GPN_COMM_ROLE_PWE_ON_SWB 				(GPN_COMM_ROLE_FILED_PWE|GPN_COMM_ROLE_RUN_FILED_SWB)

#define GPN_COMM_ROLE_INIT_ON_SUB 				(GPN_COMM_ROLE_FILED_INIT|GPN_COMM_ROLE_RUN_FILED_SUB)
#define GPN_COMM_ROLE_INIT_ON_IND 				(GPN_COMM_ROLE_FILED_INIT|GPN_COMM_ROLE_RUN_FILED_IND)
#define GPN_COMM_ROLE_INIT_ON_NMA 				(GPN_COMM_ROLE_FILED_INIT|GPN_COMM_ROLE_RUN_FILED_NMA)
#define GPN_COMM_ROLE_INIT_ON_NMB 				(GPN_COMM_ROLE_FILED_INIT|GPN_COMM_ROLE_RUN_FILED_NMB)
#define GPN_COMM_ROLE_INIT_ON_SWA 				(GPN_COMM_ROLE_FILED_INIT|GPN_COMM_ROLE_RUN_FILED_SWA)
#define GPN_COMM_ROLE_INIT_ON_SWB 				(GPN_COMM_ROLE_FILED_INIT|GPN_COMM_ROLE_RUN_FILED_SWB)

#define GPN_COMM_ROLE_STAT_ON_SUB 				(GPN_COMM_ROLE_FILED_STAT|GPN_COMM_ROLE_RUN_FILED_SUB)
#define GPN_COMM_ROLE_STAT_ON_IND 				(GPN_COMM_ROLE_FILED_STAT|GPN_COMM_ROLE_RUN_FILED_IND)
#define GPN_COMM_ROLE_STAT_ON_NMA 				(GPN_COMM_ROLE_FILED_STAT|GPN_COMM_ROLE_RUN_FILED_NMA)
#define GPN_COMM_ROLE_STAT_ON_NMB 				(GPN_COMM_ROLE_FILED_STAT|GPN_COMM_ROLE_RUN_FILED_NMB)
#define GPN_COMM_ROLE_STAT_ON_SWA 				(GPN_COMM_ROLE_FILED_STAT|GPN_COMM_ROLE_RUN_FILED_SWA)
#define GPN_COMM_ROLE_STAT_ON_SWB 				(GPN_COMM_ROLE_FILED_STAT|GPN_COMM_ROLE_RUN_FILED_SWB)

#define GPN_COMM_ROLE_CFGMGT_ON_SUB 			(GPN_COMM_ROLE_FILED_CFGMGT|GPN_COMM_ROLE_RUN_FILED_SUB)
#define GPN_COMM_ROLE_CFGMGT_ON_IND 			(GPN_COMM_ROLE_FILED_CFGMGT|GPN_COMM_ROLE_RUN_FILED_IND)
#define GPN_COMM_ROLE_CFGMGT_ON_NMA 			(GPN_COMM_ROLE_FILED_CFGMGT|GPN_COMM_ROLE_RUN_FILED_NMA)
#define GPN_COMM_ROLE_CFGMGT_ON_NMB 			(GPN_COMM_ROLE_FILED_CFGMGT|GPN_COMM_ROLE_RUN_FILED_NMB)
#define GPN_COMM_ROLE_CFGMGT_ON_SWA 			(GPN_COMM_ROLE_FILED_CFGMGT|GPN_COMM_ROLE_RUN_FILED_SWA)
#define GPN_COMM_ROLE_CFGMGT_ON_SWB 			(GPN_COMM_ROLE_FILED_CFGMGT|GPN_COMM_ROLE_RUN_FILED_SWB)

#define GPN_COMM_ROLE_SYSMGT_ON_SUB 			(GPN_COMM_ROLE_FILED_SYSMGT|GPN_COMM_ROLE_RUN_FILED_SUB)
#define GPN_COMM_ROLE_SYSMGT_ON_IND 			(GPN_COMM_ROLE_FILED_SYSMGT|GPN_COMM_ROLE_RUN_FILED_IND)
#define GPN_COMM_ROLE_SYSMGT_ON_NMA 			(GPN_COMM_ROLE_FILED_SYSMGT|GPN_COMM_ROLE_RUN_FILED_NMA)
#define GPN_COMM_ROLE_SYSMGT_ON_NMB 			(GPN_COMM_ROLE_FILED_SYSMGT|GPN_COMM_ROLE_RUN_FILED_NMB)
#define GPN_COMM_ROLE_SYSMGT_ON_SWA 			(GPN_COMM_ROLE_FILED_SYSMGT|GPN_COMM_ROLE_RUN_FILED_SWA)
#define GPN_COMM_ROLE_SYSMGT_ON_SWB 			(GPN_COMM_ROLE_FILED_SYSMGT|GPN_COMM_ROLE_RUN_FILED_SWB)

#define GPN_COMM_ROLE_FT_ON_SUB 				(GPN_COMM_ROLE_FILED_FT|GPN_COMM_ROLE_RUN_FILED_SUB)
#define GPN_COMM_ROLE_FT_ON_IND 				(GPN_COMM_ROLE_FILED_FT|GPN_COMM_ROLE_RUN_FILED_IND)
#define GPN_COMM_ROLE_FT_ON_NMA 				(GPN_COMM_ROLE_FILED_FT|GPN_COMM_ROLE_RUN_FILED_NMA)
#define GPN_COMM_ROLE_FT_ON_NMB 				(GPN_COMM_ROLE_FILED_FT|GPN_COMM_ROLE_RUN_FILED_NMB)
#define GPN_COMM_ROLE_FT_ON_SWA 				(GPN_COMM_ROLE_FILED_FT|GPN_COMM_ROLE_RUN_FILED_SWA)
#define GPN_COMM_ROLE_FT_ON_SWB 				(GPN_COMM_ROLE_FILED_FT|GPN_COMM_ROLE_RUN_FILED_SWB)

#define GPN_COMM_ROLE_OAMD_ON_SUB 				(GPN_COMM_ROLE_FILED_OAMD|GPN_COMM_ROLE_RUN_FILED_SUB)
#define GPN_COMM_ROLE_OAMD_ON_IND 				(GPN_COMM_ROLE_FILED_OAMD|GPN_COMM_ROLE_RUN_FILED_IND)
#define GPN_COMM_ROLE_OAMD_ON_NMA 				(GPN_COMM_ROLE_FILED_OAMD|GPN_COMM_ROLE_RUN_FILED_NMA)
#define GPN_COMM_ROLE_OAMD_ON_NMB 				(GPN_COMM_ROLE_FILED_OAMD|GPN_COMM_ROLE_RUN_FILED_NMB)
#define GPN_COMM_ROLE_OAMD_ON_SWA 				(GPN_COMM_ROLE_FILED_OAMD|GPN_COMM_ROLE_RUN_FILED_SWA)
#define GPN_COMM_ROLE_OAMD_ON_SWB 				(GPN_COMM_ROLE_FILED_OAMD|GPN_COMM_ROLE_RUN_FILED_SWB)

#define GPN_COMM_ROLE_SYNCED_ON_SUB 			(GPN_COMM_ROLE_FILED_SYNCED|GPN_COMM_ROLE_RUN_FILED_SUB)
#define GPN_COMM_ROLE_SYNCED_ON_IND 			(GPN_COMM_ROLE_FILED_SYNCED|GPN_COMM_ROLE_RUN_FILED_IND)
#define GPN_COMM_ROLE_SYNCED_ON_NMA 			(GPN_COMM_ROLE_FILED_SYNCED|GPN_COMM_ROLE_RUN_FILED_NMA)
#define GPN_COMM_ROLE_SYNCED_ON_NMB 			(GPN_COMM_ROLE_FILED_SYNCED|GPN_COMM_ROLE_RUN_FILED_NMB)
#define GPN_COMM_ROLE_SYNCED_ON_SWA 			(GPN_COMM_ROLE_FILED_SYNCED|GPN_COMM_ROLE_RUN_FILED_SWA)
#define GPN_COMM_ROLE_SYNCED_ON_SWB 			(GPN_COMM_ROLE_FILED_SYNCED|GPN_COMM_ROLE_RUN_FILED_SWB)

/*reserved module */
#if 0
#define GPN_COMM_ROLE_RESERVED01_ON_SUB         (GPN_COMM_ROLE_FILED_RESERVED04|GPN_COMM_ROLE_RUN_FILED_SUB)
#define GPN_COMM_ROLE_RESERVED01_ON_IND         (GPN_COMM_ROLE_FILED_RESERVED04|GPN_COMM_ROLE_RUN_FILED_IND)
#define GPN_COMM_ROLE_RESERVED01_ON_NMA         (GPN_COMM_ROLE_FILED_RESERVED04|GPN_COMM_ROLE_RUN_FILED_NMA)
#define GPN_COMM_ROLE_RESERVED01_ON_NMB         (GPN_COMM_ROLE_FILED_RESERVED04|GPN_COMM_ROLE_RUN_FILED_NMB)
#define GPN_COMM_ROLE_RESERVED01_ON_SWA         (GPN_COMM_ROLE_FILED_RESERVED04|GPN_COMM_ROLE_RUN_FILED_SWA)
#define GPN_COMM_ROLE_RESERVED01_ON_SWB         (GPN_COMM_ROLE_FILED_RESERVED04|GPN_COMM_ROLE_RUN_FILED_SWB)
#endif

/*timer sever module */

#define GPN_COMM_ROLE_CREAT(funcRole, runPlace) ((((funcRole) & (GPN_COMM_ROLE_MODU_MASK)) <<  GPN_COMM_ROLE_MODU_SHIFT) |\
												 (((runPlace) & (GPN_COMM_ROLE_RUN_MASK))<< GPN_COMM_ROLE_RUN_SHIFT))
#define GPN_COMM_FUNC_ROLE_DECODE(role)         (((role) >> (GPN_COMM_ROLE_MODU_SHIFT)) & (GPN_COMM_ROLE_MODU_MASK))
#define GPN_COMM_RUN_PLACE_DECODE(role)         (((role) >> (GPN_COMM_ROLE_RUN_SHIFT)) & (GPN_COMM_ROLE_RUN_MASK))

/*=============================================================================================================*/
/*=============================================================================================================*/
/*=============================================================================================================*/

/*slot to SLOT_BASE_CPU_COMM_ROLE transfer*/
#define GPN_COMM_CPUID_CREAT(slot)				((slot))
#define GPN_COMM_CPUID_DECOM(CPUId)				((CPUId))

#define GPN_COMM_CPUID_SLOT_00					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_00)
#define GPN_COMM_CPUID_SLOT_01					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_01)
#define GPN_COMM_CPUID_SLOT_02					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_02)
#define GPN_COMM_CPUID_SLOT_03					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_03)
#define GPN_COMM_CPUID_SLOT_04					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_04)
#define GPN_COMM_CPUID_SLOT_05					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_05)
#define GPN_COMM_CPUID_SLOT_06					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_06)
#define GPN_COMM_CPUID_SLOT_07					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_07)
#define GPN_COMM_CPUID_SLOT_08					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_08)
#define GPN_COMM_CPUID_SLOT_09					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_09)
#define GPN_COMM_CPUID_SLOT_10					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_10)
#define GPN_COMM_CPUID_SLOT_11					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_11)
#define GPN_COMM_CPUID_SLOT_12					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_12)
#define GPN_COMM_CPUID_SLOT_13					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_13)
#define GPN_COMM_CPUID_SLOT_14					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_14)
#define GPN_COMM_CPUID_SLOT_15					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_15)
#define GPN_COMM_CPUID_SLOT_16					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_16)
#define GPN_COMM_CPUID_SLOT_17					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_17)
#define GPN_COMM_CPUID_SLOT_18					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_18)
#define GPN_COMM_CPUID_SLOT_19					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_19)
#define GPN_COMM_CPUID_SLOT_20					GPN_COMM_CPUID_CREAT(GPN_SOCK_DEV_SLOT_20)

#define GPN_COMM_ROLE_MAX_SLOT_NUM              GPN_SOCK_DEV_MAX_SLOT

#define GPN_COMM_ROLE_MAX_NM_NUM                GPN_SOCK_DEV_NM_NUM
#define GPN_COMM_ROLE_NMA_INDEX                 GPN_SOCK_DEV_NMA_INDEX
#define GPN_COMM_ROLE_NMB_INDEX                 GPN_SOCK_DEV_NMB_INDEX


/*INET IP & UDP port default value define*/
/*each CPU has 3 default port*/
#define GPN_COMM_PER_CPU_PORT_NUM				GPN_DEV_CI_PER_SLOT_UPORTS
#define GPN_COMM_CPUID_DEFPORT_START			GPN_DEV_CI_DEFPORT_START

#define GPN_COMM_CPUID_DEFPORT_1_START			GPN_COMM_CPUID_DEFPORT_START
#define GPN_COMM_CPUID_DEFPORT_2_START			(GPN_COMM_CPUID_DEFPORT_1_START+GPN_COMM_ROLE_MAX_SLOT_NUM)
#define GPN_COMM_CPUID_DEFPORT_3_START			(GPN_COMM_CPUID_DEFPORT_2_START+GPN_COMM_ROLE_MAX_SLOT_NUM)
#define GPN_COMM_CPUID_DEFPORT_4_START			(GPN_COMM_CPUID_DEFPORT_3_START+GPN_COMM_ROLE_MAX_SLOT_NUM)
#define GPN_COMM_CPUID_DEFPORT_5_START			(GPN_COMM_CPUID_DEFPORT_4_START+GPN_COMM_ROLE_MAX_SLOT_NUM)
#define GPN_COMM_CPUID_DEFPORT_6_START			(GPN_COMM_CPUID_DEFPORT_5_START+GPN_COMM_ROLE_MAX_SLOT_NUM)

/*gpn_socket UDP port distribution*/
#define GPN_COMM_TRANSFER_NMA_PORT_LAB			0
#define GPN_COMM_TRANSFER_NMB_PORT_LAB			1
#define GPN_COMM_FT_NMA_PORT_LAB				2
#define GPN_COMM_FT_NMB_PORT_LAB				3
#define GPN_COMM_NMx_SYN_LAB					4
#define GPN_COMM_XXXX_LAB						5


#define GPN_COMM_CPUID_S1_DEFIP					"192.192.192.1"
#define GPN_COMM_CPUID_S1_DEFPORT_1				(GPN_COMM_CPUID_DEFPORT_1_START+0)
#define GPN_COMM_CPUID_S1_DEFPORT_2				(GPN_COMM_CPUID_DEFPORT_2_START+0)
#define GPN_COMM_CPUID_S1_DEFPORT_3				(GPN_COMM_CPUID_DEFPORT_3_START+0)
#define GPN_COMM_CPUID_S1_DEFPORT_4				(GPN_COMM_CPUID_DEFPORT_4_START+0)
#define GPN_COMM_CPUID_S1_DEFPORT_5				(GPN_COMM_CPUID_DEFPORT_5_START+0)
#define GPN_COMM_CPUID_S1_DEFPORT_6				(GPN_COMM_CPUID_DEFPORT_6_START+0)

#define GPN_COMM_CPUID_S2_DEFIP					"192.192.192.2"
#define GPN_COMM_CPUID_S2_DEFPORT_1				(GPN_COMM_CPUID_DEFPORT_1_START+1)
#define GPN_COMM_CPUID_S2_DEFPORT_2				(GPN_COMM_CPUID_DEFPORT_2_START+1)
#define GPN_COMM_CPUID_S2_DEFPORT_3				(GPN_COMM_CPUID_DEFPORT_3_START+1)
#define GPN_COMM_CPUID_S2_DEFPORT_4				(GPN_COMM_CPUID_DEFPORT_4_START+1)
#define GPN_COMM_CPUID_S2_DEFPORT_5				(GPN_COMM_CPUID_DEFPORT_5_START+1)
#define GPN_COMM_CPUID_S2_DEFPORT_6				(GPN_COMM_CPUID_DEFPORT_6_START+1)

#define GPN_COMM_CPUID_S3_DEFIP					"192.192.192.3"
#define GPN_COMM_CPUID_S3_DEFPORT_1				(GPN_COMM_CPUID_DEFPORT_1_START+2)
#define GPN_COMM_CPUID_S3_DEFPORT_2				(GPN_COMM_CPUID_DEFPORT_2_START+2)
#define GPN_COMM_CPUID_S3_DEFPORT_3				(GPN_COMM_CPUID_DEFPORT_3_START+2)
#define GPN_COMM_CPUID_S3_DEFPORT_4				(GPN_COMM_CPUID_DEFPORT_4_START+2)
#define GPN_COMM_CPUID_S3_DEFPORT_5				(GPN_COMM_CPUID_DEFPORT_5_START+2)
#define GPN_COMM_CPUID_S3_DEFPORT_6				(GPN_COMM_CPUID_DEFPORT_6_START+2)

#define GPN_COMM_CPUID_S4_DEFIP					"192.192.192.4"
#define GPN_COMM_CPUID_S4_DEFPORT_1				(GPN_COMM_CPUID_DEFPORT_1_START+3)
#define GPN_COMM_CPUID_S4_DEFPORT_2				(GPN_COMM_CPUID_DEFPORT_2_START+3)
#define GPN_COMM_CPUID_S4_DEFPORT_3				(GPN_COMM_CPUID_DEFPORT_3_START+3)
#define GPN_COMM_CPUID_S4_DEFPORT_4				(GPN_COMM_CPUID_DEFPORT_4_START+3)
#define GPN_COMM_CPUID_S4_DEFPORT_5				(GPN_COMM_CPUID_DEFPORT_5_START+3)
#define GPN_COMM_CPUID_S4_DEFPORT_6				(GPN_COMM_CPUID_DEFPORT_6_START+3)

#define GPN_COMM_CPUID_S5_DEFIP					"192.192.192.5"
#define GPN_COMM_CPUID_S5_DEFPORT_1				(GPN_COMM_CPUID_DEFPORT_1_START+4)
#define GPN_COMM_CPUID_S5_DEFPORT_2				(GPN_COMM_CPUID_DEFPORT_2_START+4)
#define GPN_COMM_CPUID_S5_DEFPORT_3				(GPN_COMM_CPUID_DEFPORT_3_START+4)
#define GPN_COMM_CPUID_S5_DEFPORT_4				(GPN_COMM_CPUID_DEFPORT_4_START+4)
#define GPN_COMM_CPUID_S5_DEFPORT_5				(GPN_COMM_CPUID_DEFPORT_5_START+4)
#define GPN_COMM_CPUID_S5_DEFPORT_6				(GPN_COMM_CPUID_DEFPORT_6_START+4)

#define GPN_COMM_CPUID_S6_DEFIP					"192.192.192.6"
#define GPN_COMM_CPUID_S6_DEFPORT_1				(GPN_COMM_CPUID_DEFPORT_1_START+5)
#define GPN_COMM_CPUID_S6_DEFPORT_2				(GPN_COMM_CPUID_DEFPORT_2_START+5)
#define GPN_COMM_CPUID_S6_DEFPORT_3				(GPN_COMM_CPUID_DEFPORT_3_START+5)
#define GPN_COMM_CPUID_S6_DEFPORT_4				(GPN_COMM_CPUID_DEFPORT_4_START+5)
#define GPN_COMM_CPUID_S6_DEFPORT_5				(GPN_COMM_CPUID_DEFPORT_5_START+5)
#define GPN_COMM_CPUID_S6_DEFPORT_6				(GPN_COMM_CPUID_DEFPORT_6_START+5)

#define GPN_COMM_CPUID_S7_DEFIP					"192.192.192.7"
#define GPN_COMM_CPUID_S7_DEFPORT_1				(GPN_COMM_CPUID_DEFPORT_1_START+6)
#define GPN_COMM_CPUID_S7_DEFPORT_2				(GPN_COMM_CPUID_DEFPORT_2_START+6)
#define GPN_COMM_CPUID_S7_DEFPORT_3				(GPN_COMM_CPUID_DEFPORT_3_START+6)
#define GPN_COMM_CPUID_S7_DEFPORT_4				(GPN_COMM_CPUID_DEFPORT_4_START+6)
#define GPN_COMM_CPUID_S7_DEFPORT_5				(GPN_COMM_CPUID_DEFPORT_5_START+6)
#define GPN_COMM_CPUID_S7_DEFPORT_6				(GPN_COMM_CPUID_DEFPORT_6_START+6)

#define GPN_COMM_CPUID_S8_DEFIP					"192.192.192.8"
#define GPN_COMM_CPUID_S8_DEFPORT_1				(GPN_COMM_CPUID_DEFPORT_1_START+7)
#define GPN_COMM_CPUID_S8_DEFPORT_2				(GPN_COMM_CPUID_DEFPORT_2_START+7)
#define GPN_COMM_CPUID_S8_DEFPORT_3				(GPN_COMM_CPUID_DEFPORT_3_START+7)
#define GPN_COMM_CPUID_S8_DEFPORT_4				(GPN_COMM_CPUID_DEFPORT_4_START+7)
#define GPN_COMM_CPUID_S8_DEFPORT_5				(GPN_COMM_CPUID_DEFPORT_5_START+7)
#define GPN_COMM_CPUID_S8_DEFPORT_6				(GPN_COMM_CPUID_DEFPORT_6_START+7)

#define GPN_COMM_CPUID_S9_DEFIP					"192.192.192.9"
#define GPN_COMM_CPUID_S9_DEFPORT_1				(GPN_COMM_CPUID_DEFPORT_1_START+8)
#define GPN_COMM_CPUID_S9_DEFPORT_2				(GPN_COMM_CPUID_DEFPORT_2_START+8)
#define GPN_COMM_CPUID_S9_DEFPORT_3				(GPN_COMM_CPUID_DEFPORT_3_START+8)
#define GPN_COMM_CPUID_S9_DEFPORT_4				(GPN_COMM_CPUID_DEFPORT_4_START+8)
#define GPN_COMM_CPUID_S9_DEFPORT_5				(GPN_COMM_CPUID_DEFPORT_5_START+8)
#define GPN_COMM_CPUID_S9_DEFPORT_6				(GPN_COMM_CPUID_DEFPORT_6_START+8)

#define GPN_COMM_CPUID_S10_DEFIP				"192.192.192.10"
#define GPN_COMM_CPUID_S10_DEFPORT_1			(GPN_COMM_CPUID_DEFPORT_1_START+9)
#define GPN_COMM_CPUID_S10_DEFPORT_2			(GPN_COMM_CPUID_DEFPORT_2_START+9)
#define GPN_COMM_CPUID_S10_DEFPORT_3			(GPN_COMM_CPUID_DEFPORT_3_START+9)
#define GPN_COMM_CPUID_S10_DEFPORT_4			(GPN_COMM_CPUID_DEFPORT_4_START+9)
#define GPN_COMM_CPUID_S10_DEFPORT_5			(GPN_COMM_CPUID_DEFPORT_5_START+9)
#define GPN_COMM_CPUID_S10_DEFPORT_6			(GPN_COMM_CPUID_DEFPORT_6_START+9)

#define GPN_COMM_CPUID_S11_DEFIP				"192.192.192.11"
#define GPN_COMM_CPUID_S11_DEFPORT_1			(GPN_COMM_CPUID_DEFPORT_1_START+10)
#define GPN_COMM_CPUID_S11_DEFPORT_2			(GPN_COMM_CPUID_DEFPORT_2_START+10)
#define GPN_COMM_CPUID_S11_DEFPORT_3			(GPN_COMM_CPUID_DEFPORT_3_START+10)
#define GPN_COMM_CPUID_S11_DEFPORT_4			(GPN_COMM_CPUID_DEFPORT_4_START+10)
#define GPN_COMM_CPUID_S11_DEFPORT_5			(GPN_COMM_CPUID_DEFPORT_5_START+10)
#define GPN_COMM_CPUID_S11_DEFPORT_6			(GPN_COMM_CPUID_DEFPORT_6_START+10)

#define GPN_COMM_CPUID_S12_DEFIP				"192.192.192.12"
#define GPN_COMM_CPUID_S12_DEFPORT_1			(GPN_COMM_CPUID_DEFPORT_1_START+11)
#define GPN_COMM_CPUID_S12_DEFPORT_2			(GPN_COMM_CPUID_DEFPORT_2_START+11)
#define GPN_COMM_CPUID_S12_DEFPORT_3			(GPN_COMM_CPUID_DEFPORT_3_START+11)
#define GPN_COMM_CPUID_S12_DEFPORT_4			(GPN_COMM_CPUID_DEFPORT_4_START+11)
#define GPN_COMM_CPUID_S12_DEFPORT_5			(GPN_COMM_CPUID_DEFPORT_5_START+11)
#define GPN_COMM_CPUID_S12_DEFPORT_6			(GPN_COMM_CPUID_DEFPORT_6_START+11)

#define GPN_COMM_CPUID_S13_DEFIP				"192.192.192.13"
#define GPN_COMM_CPUID_S13_DEFPORT_1			(GPN_COMM_CPUID_DEFPORT_1_START+12)
#define GPN_COMM_CPUID_S13_DEFPORT_2			(GPN_COMM_CPUID_DEFPORT_2_START+12)
#define GPN_COMM_CPUID_S13_DEFPORT_3			(GPN_COMM_CPUID_DEFPORT_3_START+12)
#define GPN_COMM_CPUID_S13_DEFPORT_4			(GPN_COMM_CPUID_DEFPORT_4_START+12)
#define GPN_COMM_CPUID_S13_DEFPORT_5			(GPN_COMM_CPUID_DEFPORT_5_START+12)
#define GPN_COMM_CPUID_S13_DEFPORT_6			(GPN_COMM_CPUID_DEFPORT_6_START+12)

#define GPN_COMM_CPUID_S14_DEFIP				"192.192.192.14"
#define GPN_COMM_CPUID_S14_DEFPORT_1			(GPN_COMM_CPUID_DEFPORT_1_START+13)
#define GPN_COMM_CPUID_S14_DEFPORT_2			(GPN_COMM_CPUID_DEFPORT_2_START+13)
#define GPN_COMM_CPUID_S14_DEFPORT_3			(GPN_COMM_CPUID_DEFPORT_3_START+13)
#define GPN_COMM_CPUID_S14_DEFPORT_4			(GPN_COMM_CPUID_DEFPORT_4_START+13)
#define GPN_COMM_CPUID_S14_DEFPORT_5			(GPN_COMM_CPUID_DEFPORT_5_START+13)
#define GPN_COMM_CPUID_S14_DEFPORT_6			(GPN_COMM_CPUID_DEFPORT_6_START+13)

#define GPN_COMM_CPUID_S15_DEFIP				"192.192.192.15"
#define GPN_COMM_CPUID_S15_DEFPORT_1			(GPN_COMM_CPUID_DEFPORT_1_START+14)
#define GPN_COMM_CPUID_S15_DEFPORT_2			(GPN_COMM_CPUID_DEFPORT_2_START+14)
#define GPN_COMM_CPUID_S15_DEFPORT_3			(GPN_COMM_CPUID_DEFPORT_3_START+14)
#define GPN_COMM_CPUID_S15_DEFPORT_4			(GPN_COMM_CPUID_DEFPORT_4_START+14)
#define GPN_COMM_CPUID_S15_DEFPORT_5			(GPN_COMM_CPUID_DEFPORT_5_START+14)
#define GPN_COMM_CPUID_S15_DEFPORT_6			(GPN_COMM_CPUID_DEFPORT_6_START+14)

#define GPN_COMM_CPUID_S16_DEFIP				"192.192.192.16"
#define GPN_COMM_CPUID_S16_DEFPORT_1			(GPN_COMM_CPUID_DEFPORT_1_START+15)
#define GPN_COMM_CPUID_S16_DEFPORT_2			(GPN_COMM_CPUID_DEFPORT_2_START+15)
#define GPN_COMM_CPUID_S16_DEFPORT_3			(GPN_COMM_CPUID_DEFPORT_3_START+15)
#define GPN_COMM_CPUID_S16_DEFPORT_4			(GPN_COMM_CPUID_DEFPORT_4_START+15)
#define GPN_COMM_CPUID_S16_DEFPORT_5			(GPN_COMM_CPUID_DEFPORT_5_START+15)
#define GPN_COMM_CPUID_S16_DEFPORT_6			(GPN_COMM_CPUID_DEFPORT_6_START+15)

#define GPN_COMM_CPUID_S17_DEFIP				"192.192.192.17"
#define GPN_COMM_CPUID_S17_DEFPORT_1			(GPN_COMM_CPUID_DEFPORT_1_START+16)
#define GPN_COMM_CPUID_S17_DEFPORT_2			(GPN_COMM_CPUID_DEFPORT_2_START+16)
#define GPN_COMM_CPUID_S17_DEFPORT_3			(GPN_COMM_CPUID_DEFPORT_3_START+16)
#define GPN_COMM_CPUID_S17_DEFPORT_4			(GPN_COMM_CPUID_DEFPORT_4_START+16)
#define GPN_COMM_CPUID_S17_DEFPORT_5			(GPN_COMM_CPUID_DEFPORT_5_START+16)
#define GPN_COMM_CPUID_S17_DEFPORT_6			(GPN_COMM_CPUID_DEFPORT_6_START+16)

#define GPN_COMM_CPUID_S18_DEFIP				"192.192.192.18"
#define GPN_COMM_CPUID_S18_DEFPORT_1			(GPN_COMM_CPUID_DEFPORT_1_START+17)
#define GPN_COMM_CPUID_S18_DEFPORT_2			(GPN_COMM_CPUID_DEFPORT_2_START+17)
#define GPN_COMM_CPUID_S18_DEFPORT_3			(GPN_COMM_CPUID_DEFPORT_3_START+17)
#define GPN_COMM_CPUID_S18_DEFPORT_4			(GPN_COMM_CPUID_DEFPORT_4_START+17)
#define GPN_COMM_CPUID_S18_DEFPORT_5			(GPN_COMM_CPUID_DEFPORT_5_START+17)
#define GPN_COMM_CPUID_S18_DEFPORT_6			(GPN_COMM_CPUID_DEFPORT_6_START+17)

#define GPN_COMM_CPUID_S19_DEFIP				"192.192.192.19"
#define GPN_COMM_CPUID_S19_DEFPORT_1			(GPN_COMM_CPUID_DEFPORT_1_START+18)
#define GPN_COMM_CPUID_S19_DEFPORT_2			(GPN_COMM_CPUID_DEFPORT_2_START+18)
#define GPN_COMM_CPUID_S19_DEFPORT_3			(GPN_COMM_CPUID_DEFPORT_3_START+18)
#define GPN_COMM_CPUID_S19_DEFPORT_4			(GPN_COMM_CPUID_DEFPORT_4_START+18)
#define GPN_COMM_CPUID_S19_DEFPORT_5			(GPN_COMM_CPUID_DEFPORT_5_START+18)
#define GPN_COMM_CPUID_S19_DEFPORT_6			(GPN_COMM_CPUID_DEFPORT_6_START+18)

#define GPN_COMM_CPUID_S20_DEFIP				"192.192.192.20"
#define GPN_COMM_CPUID_S20_DEFPORT_1			(GPN_COMM_CPUID_DEFPORT_1_START+19)
#define GPN_COMM_CPUID_S20_DEFPORT_2			(GPN_COMM_CPUID_DEFPORT_2_START+19)
#define GPN_COMM_CPUID_S20_DEFPORT_3			(GPN_COMM_CPUID_DEFPORT_3_START+19)
#define GPN_COMM_CPUID_S20_DEFPORT_4			(GPN_COMM_CPUID_DEFPORT_4_START+19)
#define GPN_COMM_CPUID_S20_DEFPORT_5			(GPN_COMM_CPUID_DEFPORT_5_START+19)
#define GPN_COMM_CPUID_S20_DEFPORT_6			(GPN_COMM_CPUID_DEFPORT_6_START+19)



/*CPUId and MODUId to COMM ROLE*/
#define GPN_COMM_XID_COMM_ROLE(slefCPUId, CPUId, moduId, commRole) \
if(slefCPUId == CPUId)\
{\
	commRole = moduId;\
}\
else if(moduId == GPN_SOCK_ROLE_TRANS)\
{\
	commRole = (GPN_SOCK_ROLE_NM_TO_SUB1T-1) + CPUId;\
}\
else if(moduId == GPN_SOCK_ROLE_FT)\
{\
	commRole = (GPN_SOCK_ROLE_NM_TO_SUB1F-1) + CPUId;\
}\
else\
{\
	printf("%s : err! slefCPUId %d, CPUId %d, moduId %d, commRole %d\n\r",\\
		slefCPUId , CPUId , moduId , commRole);\
}\


/*define gpn_socket INET communication ip & UDP port infomation*/
#define GPN_COMM_DEV_IP_CFG_LINE				128
#define GPN_COMM_DEV_IP_CFG_FILE_LEN			2048

/*define gpn_socket UNIX communication socket fd name infomation*/
#define GPN_COMM_DEV_UA_CFG_LEN					1024
#define GPN_COMM_UINX_ADDR_INFO_FILE			GPN_SC_UP_RAM_NODE(gpnTransUNIXInfo.info);

typedef struct _gpnSockRoleNameTp_
{
	UINT32 sockRoleId;
	const char *processName;
	const char *shortName;
}gpnSockRoleNameTp;

typedef struct _gpnSockUNIXLinkTp_
{
	UINT32 selfCommId;

	/*contain socket link cfg info for role comm ID*/
	UINT8 LinkCfg[GPN_SOCK_INS_ROLE_ID_MAX+1];

}gpnSockUNIXLinkTp;

typedef struct _UNIXSockInfo_
{
	UINT32 sockSta;
	INT32 sockType;
	struct sockaddr_un addrSev;
	struct sockaddr_un addrCli;
}UNIXSockInfo;

typedef struct _INETSockInfo_
{
	UINT32 sockSta;
	INT32 sockType;
	struct sockaddr_in addrSev;
	/*gpn_transfer 	use port1 whit NMa*/
	/*gpn_transfer 	use port2 whit NMb*/
	/*gpn_ft		use port3 whit NMa*/
	/*gpn_ft 		use port4 whit NMb*/
	/*NMx_syn	use port5 whit NMb*/
	UINT16 SUdpPort[GPN_COMM_PER_CPU_PORT_NUM];
	struct sockaddr_in addrCli;
	UINT16 CUdpPort[GPN_COMM_PER_CPU_PORT_NUM];
}INETSockInfo;

typedef struct _gpnRoleDate_
{
	UINT32 role;
	UINT32 CPUId;/*soft running witch CPU*/
	UINT32 moduId;
	UINT32 localSrc;
	/*assist for nm-syn msg comm*/
	UINT32 NMaCPUId;
	UINT32 NMbCPUId;

	/*for GPN_XXX instance role UNIX socket fd*/
	UNIXSockInfo moduUNIXSockInfo[GPN_SOCK_INS_ROLE_ID_MAX+1];
	
	/*for Timer-Server UNIX socket fd*/
	UNIXSockInfo timerSevUNIXSockInfo;

	/*for Transfer-INET socket fd*/
	INETSockInfo transSubINETSockInfo[GPN_COMM_ROLE_MAX_SLOT_NUM];

	/*for GPN_FT-INET socket fd*/
	INETSockInfo FTSubINETSockInfo[GPN_COMM_ROLE_MAX_SLOT_NUM];

	/*for GPN_NM_SYN-INET socket fd*/
	INETSockInfo NMSYNSubINETSockInfo[GPN_COMM_ROLE_MAX_NM_NUM];
	
}gpnRoleDate;

typedef struct _sockCommData_
{
	gpnRoleDate gRoleData;
	stSockFdSet gstFdSet;
}sockCommData;

extern sockCommData gSockCommData;

UINT32 gpnSockRoleProcNameGet(UINT32 sockRole, char **pprPName, UINT32 *len);
UINT32 gpnSockRoleShortNameGet(UINT32 sockRole, char **pprSName, UINT32 *len);
UINT32 gpnSockRoleIdGet(char *psockRoleName, UINT32 *psockRole);
UINT32 gpnSockRoleCreat(UINT32 funRole, UINT32 *prole);
UINT32 gpnSockRoleModuValidCheck(UINT32 moduId);
UINT32 gpnSockRoleInfoCheck(UINT32 role);
UINT32 gpnCommSubDevCommInit(INETSockInfo *pSubCliAddr);
UINT32 gpnCommDevCommInfo2SubDevCommCfg(INETSockInfo *pSubCliAddr);
UINT32 gpnCommSubDevCommCfg(INETSockInfo *pSubCliAddr);
UINT32 gpnSockCommGetSelfSlot(UINT32 *pselfSlot);
UINT32 gpnSockCommGetNMSlot(UINT32 *pNMaSlot, UINT32 *pNMbSlot);
UINT32 gpnCommRoleInit(UINT32 role, UINT32 selfSlot, gpnRoleDate *gpRoleInfo, INETSockInfo *pSubCliAddr);
UINT32 gpnSockCommCreatUNIXCommInfo(UINT32 localModu, UINT32 lpModu, gpnRoleDate *gpRoleInfo, gpnSockUNIXLinkTp *pgpnSCUnixLink);
UINT32 gpnSockCommTimerSevInit(UINT32 role, gpnRoleDate *gpRoleInfo);
UINT32 gpnSockCommUNIXCfgAbleRoleLinkInit(UINT32 role, gpnRoleDate *gpRoleInfo);
UINT32 gpnSockCommTransINETLinkInit(UINT32 role, UINT32 selfSlot, gpnRoleDate *gpRoleInfo, INETSockInfo *pSubCliAddr);
UINT32 gpnSockCommFTINETLinkInit(UINT32 role, UINT32 selfSlot, gpnRoleDate *gpRoleInfo, INETSockInfo *pSubCliAddr);
UINT32 gpnSockCommNMSYNINETLinkInit(UINT32 role, UINT32 selfSlot, gpnRoleDate *gpRoleInfo, INETSockInfo *pSubCliAddr);
UINT32 gpnSockCommMsgDst2RoleSeat(stSockFdSet *pstFdSet, UINT32 dricId, UINT32 *pfdSeat);
UINT32 gpnSockCommXID2UnixCommRoleSeat(UINT32 moduId, UINT32 *pfdSeat);
UINT32 gpnSockCommXID2UnixTimerRoleSeat(UINT32 moduId, UINT32 *pfdSeat);
UINT32 gpnSockCommXID2InetTransferCommRoleSeat(UINT32 cpuId, UINT32 *pfdSeat);
UINT32 gpnSockCommXID2InetFtCommRoleSeat(UINT32 cpuId, UINT32 *pfdSeat);
UINT32 gpnSockCommXID2InetNMxSynCommRoleSeat(UINT32 NMId, UINT32 *pfdSeat);
UINT32 gpnSockCommCreatUNIXCommRoleFd(gpnRoleDate *pRoleInfo, stSockFdSet *pstFdSet);
UINT32 gpnSockCommCreatUNIXTimerFd(gpnRoleDate *pRoleInfo, stSockFdSet *pstFdSet);
UINT32 gpnSockCommCreatTransferINETFd(gpnRoleDate *pRoleInfo, stSockFdSet *pstFdSet);
UINT32 gpnSockCommCreatFTINETFd(gpnRoleDate *pRoleInfo, stSockFdSet *pstFdSet);
UINT32 gpnSockCommCreatNMSYNINETFd(gpnRoleDate *pRoleInfo, stSockFdSet *pstFdSet);
UINT32 gpnSockCommDifTimerInit(UINT32 role);
UINT32 gpnSockInstanceInit(gpnRoleDate *pRoleInfo, stSockFdSet *pstFdSet, UINT32 slot);
UINT32 gpnSockCommInit(gpnRoleDate *pRoleInfo, stSockFdSet *pstFdSet, UINT32 funRole);

#ifdef    __cplusplus
}
#endif /* __cplusplus */

#endif /*_GPN_SOCK_COMM_ROLE_MAN_H_*/

