/*
* Note: this file originally auto-generated by mib2c using
*       version : 1.0.0 $ of : mib2c.snmp_handler.conf,v $ zhongjh@huahuan.com
*/
 
#ifndef _ALARMTRAP_H_
#define _ALARMTRAP_H_


void 
send_alarmProductTrap_trap(unsigned int *alarmTrapTableDataRow);
void 
send_alarmDisappearTrap_trap(unsigned int *alarmTrapTableDataRow);
void 
send_alarmEventReportTrap_trap(unsigned int *alarmTrapTableDataRow);
void 
send_alarmReverseAutoRecTrap_trap(unsigned int *alarmTrapTableDataRow);

/* trap declarations */
int 
alarmNotification(unsigned int clientreg, void *clientarg);

#endif  /*_ALARMTRAP_H_*/

